// Highlighted sidebar items
export const NEW = ['Fluid Glass', 'Cubes', 'Masonry', 'Text Trail', 'Curved Loop', 'Magic Bento', 'Ripple Grid'];
export const UPDATED = ['Split Text', 'Star Border'];

// Used for main sidebar navigation
export const CATEGORIES = [
  {
    name: 'Text Animations',
    subcategories: [
      'Split Text',
      'Blur Text',
      'Circular Text',
      'Shiny Text',
      'Text Pressure',
      'Curved Loop',
      'Fuzzy Text',
      'Gradient Text',
      'Text Trail',
      'Falling Text',
      'Text Cursor',
      'Decrypted Text',
      'True Focus',
      'Scroll Float',
      'Scroll Reveal',
      'ASCII Text',
      'Scramble Text',
      'Rotating Text',
      'Glitch Text',
      'Scroll Velocity',
      'Variable Proximity',
      'Count Up',
    ]
  },
  {
    name: 'Animations',
    subcategories: [
      'Animated Content',
      'Fade Content',
      'Pixel Transition',
      'Glare Hover',
      'Magnet Lines',
      'Click Spark',
      'Magnet',
      'Pixel Trail',
      'Cubes',
      'Metallic Paint',
      'Noise',
      'Crosshair',
      'Image Trail',
      'Ribbons',
      'Splash Cursor',
      'Meta Balls',
      'Blob Cursor',
      'Star Border'
    ]
  },
  {
    name: 'Components',
    subcategories: [
      'Animated List',
      'Magic Bento',
      'Circular Gallery',
      'Stack',
      'Fluid Glass',
      'Tilted Card',
      'Masonry',
      'Chroma Grid',
      'Folder',
      'Model Viewer',
      'Lanyard',
      'Profile Card',
      'Dock',
      'Gooey Nav',
      'Pixel Card',
      'Carousel',
      'Spotlight Card',
      'Flying Posters',
      'Card Swap',
      'Infinite Scroll',
      'Glass Icons',
      'Decay Card',
      'Flowing Menu',
      'Elastic Slider',
      'Counter',
      'Infinite Menu',
      'Rolling Gallery',
      'Stepper',
      'Bounce Cards'
    ],
  },
  {
    name: 'Backgrounds',
    subcategories: [
      'Silk',
      'Aurora',
      'Beams',
      'Lightning',
      'Balatro',
      'Dither',
      'Ripple Grid',
      'Shape Blur',
      'Dot Grid',
      'Threads',
      'Hyperspeed',
      'Iridescence',
      'Grid Distortion',
      'Ballpit',
      'Orb',
      'Grid Motion',
      'Liquid Chrome',
      'Squares',
      'Letter Glitch',
      'Particles',
      'Waves'
    ],
  }
];